package view;
import model.Database;
import javax.swing.*;
import java.sql.*;

public class Leaderboard extends javax.swing.JFrame {
    
    public Leaderboard() {
        initComponents();
        updateLeaderboard(); // Panggil fungsi untuk mengupdate leaderboard saat frame dibuka
        startAutoUpdate();   // Mulai auto-update leaderboard secara periodik

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kembaliButton = new javax.swing.JButton();
        podium2Points = new javax.swing.JLabel();
        podium3Points = new javax.swing.JLabel();
        podium1Points = new javax.swing.JLabel();
        podium3 = new javax.swing.JLabel();
        podium2 = new javax.swing.JLabel();
        podium1 = new javax.swing.JLabel();
        Leaderboard = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kembaliButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/KembaliButton.png"))); // NOI18N
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });
        getContentPane().add(kembaliButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 30));

        podium2Points.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        podium2Points.setForeground(new java.awt.Color(255, 255, 0));
        podium2Points.setText("Points");
        getContentPane().add(podium2Points, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        podium3Points.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        podium3Points.setForeground(new java.awt.Color(255, 255, 0));
        podium3Points.setText("Points");
        getContentPane().add(podium3Points, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        podium1Points.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        podium1Points.setForeground(new java.awt.Color(255, 255, 0));
        podium1Points.setText("Points");
        getContentPane().add(podium1Points, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        podium3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        podium3.setForeground(new java.awt.Color(255, 255, 255));
        podium3.setText("Podium 3");
        getContentPane().add(podium3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        podium2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        podium2.setForeground(new java.awt.Color(255, 255, 255));
        podium2.setText("Podium 2");
        getContentPane().add(podium2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        podium1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        podium1.setForeground(new java.awt.Color(255, 255, 255));
        podium1.setText("Podium 1");
        getContentPane().add(podium1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        Leaderboard.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Leaderboard.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Leaderboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 220, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Leaderboard.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        MenuUser menu = new MenuUser();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_kembaliButtonActionPerformed

    private void updateLeaderboard() {
        Connection conn = null;
        StringBuilder othersText = new StringBuilder("<html>");
        try {
            conn = Database.connect();
            String query = "SELECT Username, poin FROM users WHERE role != 'admin' ORDER BY poin DESC LIMIT 20";
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            int rank = 1;
            while (rs.next()) {
                String username = rs.getString("Username");
                int poin = rs.getInt("poin");

                if (rank == 1) {
                    podium1.setText(username);
                    podium1Points.setText(poin + " poin");
                } else if (rank == 2) {
                    podium2.setText(username);
                    podium2Points.setText(poin + " poin");
                } else if (rank == 3) {
                    podium3.setText(username);
                    podium3Points.setText(poin + " poin");
                } else {
                    othersText.append(rank).append(". ").append(username).append(" - ").append(poin).append(" poin<br>");
                }
                rank++;
            }
            othersText.append("</html>");
            Leaderboard.setText(othersText.toString());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        } finally {
            if (conn != null) {
                Database.disconnect();
            }
        }
    }
    
    private void startAutoUpdate() {
        Timer timer = new Timer(5000, e -> updateLeaderboard());
        timer.start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leaderboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Leaderboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JLabel podium1;
    private javax.swing.JLabel podium1Points;
    private javax.swing.JLabel podium2;
    private javax.swing.JLabel podium2Points;
    private javax.swing.JLabel podium3;
    private javax.swing.JLabel podium3Points;
    // End of variables declaration//GEN-END:variables
}
