/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Muhammad Rizky S
 */
public class MenuUser extends javax.swing.JFrame {

    /**
     * Creates new form LoginAdminView
     */
    public MenuUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutButton = new javax.swing.JButton();
        setorSampahButton = new javax.swing.JButton();
        tukarPoinButton = new javax.swing.JButton();
        leaderboardButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LogoutButton.png"))); // NOI18N
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 90, 30));

        setorSampahButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/SetorSampahButton.png"))); // NOI18N
        setorSampahButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setorSampahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setorSampahButtonActionPerformed(evt);
            }
        });
        getContentPane().add(setorSampahButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 140, 140));

        tukarPoinButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TukarPoinButton.png"))); // NOI18N
        tukarPoinButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tukarPoinButton.setDefaultCapable(false);
        tukarPoinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tukarPoinButtonActionPerformed(evt);
            }
        });
        getContentPane().add(tukarPoinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 140, 140));

        leaderboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LeaderboardButton.png"))); // NOI18N
        leaderboardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leaderboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderboardButtonActionPerformed(evt);
            }
        });
        getContentPane().add(leaderboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 140, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/MenuUser.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        LoginView login = new LoginView();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void setorSampahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setorSampahButtonActionPerformed
        SetorSampah setor = new SetorSampah();
        setor.setVisible(true);
        setor.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_setorSampahButtonActionPerformed

    private void tukarPoinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tukarPoinButtonActionPerformed
        TukarPoin tukar = new TukarPoin();
        tukar.setVisible(true);
        tukar.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_tukarPoinButtonActionPerformed

    private void leaderboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderboardButtonActionPerformed
        Leaderboard rank = new Leaderboard();
        rank.setVisible(true);
        rank.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_leaderboardButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton leaderboardButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton setorSampahButton;
    private javax.swing.JButton tukarPoinButton;
    // End of variables declaration//GEN-END:variables
}
